services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: push-notification
    image: duynguyen03/push-notification-htn:v1
    ports:
      - "8080:8080"
    env_file:
      - .env