services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: push-notification
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NOTIFICATION_HUB_NAME=heatlh_management_message_hub
      - NOTIFICATION_HUB_CONNECTION_STRING=Endpoint=sb://test-cloud-message-health-management.servicebus.windows.net/;SharedAccessKeyName=DefaultFullSharedAccessSignature;SharedAccessKey=Gen/f7OU35JcwGm2VGvYQk/ohca5OGegj2L6dbgUm1g=
      - FIREBASE_CONFIG_FILE=firebase.json
    env_file:
      - .env
    networks:
      - health-management_health-management-network

networks:
    health-management_health-management-network:
        driver: bridge
        external: true
